version: '3.2'
services:
    nginx_instance:
        image: nginx
        networks:
            - lemp_net
        expose:
            - 80
        environment:
            VIRTUAL_HOST: 127.0.0.1
        volumes:
            # not indispensable since it would be set by php-fpm instance before the startup of nginx instance
            # - ./www:/usr/share/nginx/html
            - ./nginx/default:/etc/nginx/conf.d/default.conf
            - ./logs/nginx_access.log:/var/log/nginx/default_access.log
            - ./logs/nginx_error.log:/var/log/nginx/default_error.log
        restart: always
        depends_on:
            - fpm_instance

    fpm_instance:
        #image: php:fpm
        # build a fpm image with redis and mysqli extension
        build: ./fpm/
        networks:
            lemp_net:
                aliases:
                    - lemp_fpm
        expose:
            - "9000"
        volumes:
            - ./www:/usr/share/nginx/html
        depends_on:
            - mysql_instance
            - redis_instance

    mysql_instance:
        image: mysql:8.0
        networks:
            lemp_net:
                aliases:
                    - lemp_mysql
        environment: 
            # set root password
            MYSQL_ROOT_PASSWORD: "123456"
            # create a database named "lemp" and create a user along with its password
            MYSQL_DATABASE: 'lemp'
            MYSQL_USER: 'l'
            MYSQL_PASSWORD: '123456'
        restart: always

    redis_instance:
        image: redis
        networks:
            lemp_net:
                aliases:
                    - lemp_redis
        # start Redis instance with specified config file
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        restart: always

networks:
    lemp_net:
        external:
            name: nginxproxy_damn
